<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-26T19:56:27 IST" name="Default suite" finished-at="2023-06-26T19:57:17 IST" duration-ms="50276">
    <groups>
    </groups>
    <test started-at="2023-06-26T19:56:27 IST" name="Default test" finished-at="2023-06-26T19:57:17 IST" duration-ms="50276">
      <class name="com.wl.userList.ReportAccess_TC2">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.wl.userList.ReportAccess_TC2@9597028]" started-at="2023-06-26T19:56:27 IST" name="beforeSuite" finished-at="2023-06-26T19:56:27 IST" duration-ms="156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.wl.userList.ReportAccess_TC2@9597028]" started-at="2023-06-26T19:56:27 IST" name="loadConfig" finished-at="2023-06-26T19:56:27 IST" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="LaunchApp()[pri:0, instance:com.wl.userList.ReportAccess_TC2@9597028]" started-at="2023-06-26T19:56:27 IST" name="LaunchApp" finished-at="2023-06-26T19:56:32 IST" duration-ms="5385" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApp -->
        <test-method signature="verifyAddNewReportFunction()[pri:0, instance:com.wl.userList.ReportAccess_TC2@9597028]" started-at="2023-06-26T19:56:32 IST" name="verifyAddNewReportFunction" finished-at="2023-06-26T19:57:16 IST" duration-ms="44318" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.wl.userList.ReportAccess_TC2.verifyAddNewReportFunction(ReportAccess_TC2.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddNewReportFunction -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.wl.userList.ReportAccess_TC2@9597028]" started-at="2023-06-26T19:57:16 IST" name="TearDown" finished-at="2023-06-26T19:57:17 IST" duration-ms="522" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.wl.userList.ReportAccess_TC2@9597028]" started-at="2023-06-26T19:57:17 IST" name="afterSuite" finished-at="2023-06-26T19:57:17 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.wl.userList.ReportAccess_TC2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
